# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GhiblisCharacterSearch' do
	pod 'Alamofire', '~> 5.0.0-beta.6'
	pod 'Kingfisher', '~> 5.7'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GhiblisCharacterSearch

  target 'GhiblisCharacterSearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GhiblisCharacterSearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
